### PR TITLE
Port stack cradle to windows reusing cabal one

### LINKED ISSUE #11: invalid argument (Exec format error)
I don't know if this is the right repository to raise the issue since I'm getting it by invoking "hie-core" in my project(s).

Anyways, when running hie-core in any of my stack projects I get something like this:

```
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "C:\\Users\\darwi\\Projects\\basic", cradleOptsProg = CradleAction: stack}

[2/6] Converting Cradle to GHC session
#!/usr/bin/env bash
if [ "$1" == "--interactive" ]; then
  pwd
  echo "$@"
else
  ghc "$@"
fi

res
  (ExitFailure 1,"C:\\msys64\\tmp\\wra530A: startProcess: invalid argument (Exec format error)\n",["-package-db","C:\\Users\\darwi\\Projects\\basic\\.stack-work\\install\\5fdbb79e\\pkgdb","-package-db","C:\\sr\\snapshots\\c6f920a2\\pkgdb","-package-db","C:\\Users\\darwi\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.6.4\\lib\\package.conf.d"],"")
hie-core.exe: CradleError "C:\\msys64\\tmp\\wra530A: startProcess: invalid argument (Exec format error)\n"
```

I'm on Windows 10 64bit. Let me know what additional info you want me to provide.
Also, sorry if this is unrelated to hie-bios. hie-core doesn't seem to have a dedicated issue board.

### LINKED ISSUE #49: hie-bios does not work with stack on Windows 10
I've tried to run ghcide with default stack-based project but failed because of the problem in hie-bios (also see digital-asset/ghcide#68):

```shell
λ stack -v-version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
λ stack new ghcide-setup
...
λ cd ghcide-setup\
...
λ stack build hie-bios ghcide --copy-compiler-tool
...
λ stack exec ghcide
Starting ghcide (GHC v8.6)
C:\Dev\learning\ghcide-setup
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "C:\\Dev\\learning\\ghcide-setup", cradleOptsProg = CradleAction: stack}

[2/6] Converting Cradle to GHC session
#!/usr/bin/env bash
if [ "$1" == "--interactive" ]; then
  pwd
  echo "$@"
else
  ghc "$@"
fi

ghcide.EXE: (ExitFailure 1,"stty: '\1057\1027\1057\8218\1056\176\1056\1029\1056\1169\1056\176\1057\1026\1057\8218\1056\1029\1057\8249\1056\8470 \1056\1030\1056\1030\1056\1109\1056\1169': Inappropriate ioctl for device\n","")
CallStack (from HasCallStack):
  error, called at src\HIE\Bios\Cradle.hs:217:18 in hie-bios-0.1.1-BtqPrxfQWIRF4Jj9iic9A:HIE.Bios.Cradle
```

### PR DESCRIPTION
**Pull request by jneira**
* Reusing `getCabalWrapperTool`
* Tested locally in windows 7
* Hopefully fixes #49, maybe #11 and partially #33 
* Output:
```console
D:\ws\haskell\stack-test>hie-bios check src\Lib.hs
cradle
  Cradle {cradleRootDir = "D:\\ws\\haskell\\stack-test", cradleOptsProg = Cradle
Action: stack}
[1 of 1] Compiling Main             ( C:\TEMP\wra9706.hs, C:\TEMP\wra9706.o )
Linking C:\TEMP\wra9727.exe ...
setTargets
  (src\Lib.hs , src\Lib.hs)
  [*src\Lib.hs]
modGraph
  [ModSummary {
      ms_hs_date = 2019-09-19 10:48:00.2052186 UTC
      ms_mod = Lib,
      ms_textual_imps = [(Nothing, Prelude), (Nothing, Data.Bifunctor)]
      ms_srcimps = []
   }]
modGraph
  [ModLocation {ml_hs_file = Just "src\\Lib.hs", ml_hi_file = "C:\\Users\\user\\A
ppData\\Local\\haskell-ide-engine\\3b7875f2994913e87022150ffb4d1f15c9fcf26f\\Lib
.hi", ml_obj_file = "D:\\ws\\haskell\\stack-test\\.stack-work\\odir\\Lib.o"}]
hidir
  Just [C, :, \, U, s, e, r, s, \, u, s, e, r, \, A, p, p, D, a, t, a,
        \, L, o, c, a, l, \, h, a, s, k, e, l, l, -, i, d, e, -, e, n, g,
        i, n, e, \, 3, b, 7, 8, 7, 5, f, 2, 9, 9, 4, 9, 1, 3, e, 8, 7, 0,
        2, 2, 1, 5, 0, f, f, b, 4, d, 1, f, 1, 5, c, 9, f, c, f, 2, 6, f]
src\Lib.hs:16:5:Warning: Defined but not used: data constructor ‘Const’
src\Lib.hs:17:5:Warning: Defined but not used: data constructor ‘X’
src\Lib.hs:18:5:Warning: Defined but not used: data constructor ‘Cos’
.......
src\Lib.hs:76:1:Warning: Defined but not used: ‘simplify’
```

### CODE REVIEW

File: src/HIE/Bios/Cradle.hs [hunk 1]
```diff
@@ -229,6 +229,7 @@ getCabalWrapperTool = do
         return wrapper_fp
       else do
         writeSystemTempFile "bios-wrapper" cabalWrapper
+  -- TODO: This isn't portable for windows
```
Comment (mpickering) [inline src/HIE/Bios/Cradle.hs]: I think it is portable, because the definition comes from `unix-compat`, at least it works correctly?

**Comment by mpickering** [comment]
Yes, good point.

File: src/HIE/Bios/Cradle.hs (hunk 1 above)
Comment (jneira) [reply src/HIE/Bios/Cradle.hs]: yeah, it does so it could be deleted (i kept the existing comment without too much thinking)
